export const mockProducts = [
  {
    id: "1",
    name: "Cappuccino",
    category: "COFFEE",
    description: "Espresso with steamed milk foam - balanced, creamy, and aromatic",
    pricePhp: 120,
    imageUrl: new URL("../../assets/Cappucino.png", import.meta.url).href,
    stock: 30,
    rating: 4.9,
  },
  {
    id: "2",
    name: "Espresso",
    category: "COFFEE",
    description: "Concentrated black coffee shot - bold, intense, and rich",
    pricePhp: 85,
    imageUrl: new URL("../../assets/Espresso.png", import.meta.url).href,
    stock: 20,
    rating: 4.7,
  },
  {
    id: "3",
    name: "Americano",
    category: "COFFEE",
    description: "Espresso diluted with hot water - clean and strong",
    pricePhp: 95,
    imageUrl: new URL("../../assets/Americano.png", import.meta.url).href,
    stock: 15,
    rating: 4.6,
  },
  {
    id: "4",
    name: "Latte",
    category: "COFFEE",
    description: "Espresso with steamed milk - smooth, milky, with optional art",
    pricePhp: 135,
    imageUrl: new URL("../../assets/Latte.png", import.meta.url).href,
    stock: 0,
    rating: 4.8,
  },
  {
    id: "5",
    name: "Tuna Salad",
    category: "FOOD",
    description: "Fresh tuna with garden greens, mayo dressing, and croutons",
    pricePhp: 180,
    imageUrl: new URL("../../assets/Tuna Salad.png", import.meta.url).href,
    stock: 12,
    rating: 4.8,
  },
  {
    id: "6",
    name: "White Wine",
    category: "BEVERAGE",
    description: "House-selected dry white wine - crisp and lightly chilled",
    pricePhp: 250,
    imageUrl: new URL("../../assets/White Wine.png", import.meta.url).href,
    stock: 7,
    rating: 4.4,
  },
  {
    id: "7",
    name: "Profiterol",
    category: "FOOD",
    description: "Choux pastry filled with cream, drizzled with chocolate sauce",
    pricePhp: 150,
    imageUrl: new URL("../../assets/Profiterol.png", import.meta.url).href,
    stock: 14,
    rating: 4.8,
  },
];
